function [Tr, fluct_rain_Tr, fluct_flow_Tr, fluct_bivariate_Tr]= STEP1_STEP2_Tr_and_fluctuations_timeseries (rain, flow, rain_min, max_window)
%This function estimate the average catchment resonse time using the DMCA
%method and using the window length correspondent to Tr produces the rain
%fluctuation, flow fluctuations and bivariate fluctuations time series
%which are going to be used to identify the events.

%INPUT:
%rain: rainfall time series as a n x 1 column vector [mm/h]
%flow: streamflow or runoff time series as a n x 1 column vector [mm/h]
%rain_min: minimum rainfall intensity considered significant at the
%          resolution of the data (e.g. 0.1 mm/h at hourly scale or follow guidelines in Appendix A) [mm/h]
%max_window: maximum window tested for the estimate of catchment response time. Set it sensibly according to the
%            resolution of your data (e.g. hourly data, max_window=300 means that the
%            catchment response time can be maximum 300hours/2 = 150hours =~ 6days)[-]

%OUTPUT:
%Tr: catchment response time in number of timesteps
%fluct_rain_Tr: rain fluctuations with window associated to catchment
%               response time corrected using the rainfall fluctuation
%               tolerance (tol_fluct_rain, in this function)
%fluct_flow_Tr: flow fluctuations with window associated to catchment response time
%fluct_bivariate_Tr: product of fluct_rain_Tr and fluct_flow_Tr

%ROUTINE

    %Tr ESTIMATE
    rain=rain'; %row vector
    flow=flow'; %row vector
    rain_int=cumsum(rain, 'omitnan'); %cumulating rainfall timeseries (Eq.1 in Giani et al., 2021)
    flow_int=cumsum(flow, 'omitnan'); %cumulating streamflow timeseries (Eq.2 in Giani et al., 2021)
    T=length(rain); %length of the timeseries

    for window=3:2:max_window
        rain_mean((window-1)/2,:)=movmean(rain_int, window); %moving average on the integrated rainfall timeseries (Eq.5 in Giani et al., 2021)
        flow_mean((window-1)/2,:)=movmean(flow_int, window); %moving average on the integrated streamflow timeseries (Eq.6 in Giani et al., 2021)
        fluct_rain((window-1)/2,:)=rain_int-rain_mean((window-1)/2,:);
        F_rain((window-1)/2)=(1/(T-window+1))*nansum((fluct_rain((window-1)/2,window-0.5*(window-1):T-0.5*(window-1))).^2); %Squared rainfall fluctuations (Eq.3 in Giani et al., 2021)
        fluct_flow((window-1)/2,:)=flow_int-flow_mean((window-1)/2,:);
        F_flow((window-1)/2)=(1/(T-window+1))*nansum((fluct_flow((window-1)/2,window-0.5*(window-1):T-0.5*(window-1))).^2); %Squared streamflow fluctuations (Eq.4 in Giani et al., 2021)
        F_rain_flow((window-1)/2)=(1/(T-window+1))*nansum(fluct_rain((window-1)/2,window-0.5*(window-1):T-0.5*(window-1)).*fluct_flow((window-1)/2,window-0.5*(window-1):T-0.5*(window-1))); %Bivariate rainfall-streamflow fluctuations (Eq.7 in Giani et al., 2021)
        rho((window-1)/2)=F_rain_flow((window-1)/2)/(sqrt(F_rain((window-1)/2))*sqrt(F_flow((window-1)/2))); %DMCA-based correlation coefficent (Eq.8 in Giani et al., 2021)
    end
    position_minimum=find(rho==nanmin(rho));
    Tr=position_minimum; 

    %FLUCTUATIONS TIME SERIES FOR WINDOW LENGTH ASSOCITED TO Tr
    tol_fluct_rain= (rain_min/(2*Tr+1))*(((2*Tr+1)-1)/2);%maximum absolute fluctuation generated by rain_min (Eq. 1 in Giani et al., currently in review with Lmin=2*Tr+1)
    tol_fluct_flow= flow_int(end)/1e15; %this is to avoid errors caused by the calculator when differences are smaller than Matlab eps
    fluct_rain(position_minimum,abs(fluct_rain(position_minimum,:))<tol_fluct_rain)=0; %setting to zero differences lower than tol_fluct_rain 
    fluct_flow(position_minimum,abs(fluct_flow(position_minimum,:))<tol_fluct_flow)=0; %setting to zero differences lower than tol_fluct_flow 

    fluct_rain_Tr=fluct_rain(position_minimum,:);
    fluct_flow_Tr=fluct_flow(position_minimum,:);
    fluct_bivariate_Tr=fluct_rain_Tr.*fluct_flow_Tr;
end

  
